platform:ios, "7.0"

#pod 'AFNetworking', '2.5.3'
pod 'AFNetworking', '~>3.1.0'
pod 'MJRefresh', '~>3.1.10'
pod 'SlimeRefresh', '~>0.0.1'
pod 'SDWebImage', '~>3.7.6'
pod 'Masonry', '~>1.0.0'
pod 'MBProgressHUD', '~>0.9.2'
pod 'MJExtension', '~>3.0.10'
#Tnar抽屉
pod 'REFrostedViewController', '~>2.4.8'
#HuNan抽屉
pod 'ViewDeck', '~>2.4.2'
#图片轮播
pod 'SDCycleScrollView', '~>1.65'
#大图浏览
pod 'MWPhotoBrowser', '~>2.1.2'
#跑马灯
pod 'MarqueeLabel', '~>2.7.5'
#解压
pod 'ZipArchive', '~>1.4.0'
#多图片选择
pod 'ELCImagePickerController', '~>0.2.0'
pod 'TZImagePickerController', '~>1.5.0'
#pod 'DKImagePickerController'	#swift

pod 'AMap3DMap', '~>4.0.3'
pod 'AMapNavi', '~>2.0.0'
pod 'AMapSearch', '~>4.0.0'
pod 'JPush', '~>2.1.8'
#pod 'libWeChatSDK', '~>1.7.1'
#pod 'TencentOpenAPIV2_3', '~>3.1.0'
#pod 'WeiboSDK', '~>3.1.3'
pod 'UMengAnalytics-NO-IDFA', '~>4.0.5'

#pod 'UMengSocialCOM', '~>5.2.1'    #导入平台过多，而且AlipayShare编译失败（需要ios8）

pod 'WebViewJavascriptBridge', '~>5.0.5'
pod 'BButton', '~>4.0.2'

pod 'TBActionSheet', '~>1.4.2'
#圆饼图 swift
#use_frameworks!
#pod 'Charts', '~>2.2.5'


pod 'DZNEmptyDataSet'           #空table样式
pod 'MagicalRecord'             #Core data
pod 'ChameleonFramework'        #基础扁平化颜色

#use_frameworks!
#pod 'TextFieldEffects'
#pod 'IBInspectable'
#pod 'IBDesignable'

pod 'GPUImage'
pod 'SlackTextViewController'
pod 'MGSwipeTableCell'
#pod 'Spring'       #swift
pod 'ios-charts'


pod 'SMSSDK'    #需要MOBFoundation_IDFA公共库
#ShareSDK begin
# 主模块(必须)
pod 'ShareSDK3'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
#pod 'MOBFoundation'     #NO IDFA
pod 'MOBFoundation_IDFA'     #IDFA
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面则需要)
pod 'ShareSDK3/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
#ShareSDK end

#pgy
pod 'Pgyer', '~>2.8.4'
pod 'PgyUpdate', '~>1.2'

#DeviceUtil helps identifying the exact harware type of the device. e.g. iPhone 6 or iPhone 6s.
pod 'DeviceUtil', '~>1.3.7'

#EaseMob  2.x
#pod 'EaseMobSDK', '~>2.2.6'
#pod 'EaseMobSDKFull', '~>2.2.6'
#EaseMob  3.x
#pod 'HyphenateSDK', '~>3.1.3'
pod 'HyphenateFullSDK', '~>3.1.3'

#TabBar
#https://github.com/ChenYilong/CYLTabBarController
pod 'CYLTabBarController', '~>1.5.6'

#https://github.com/iTofu/LCTabBarController
#pod 'LCTabBarController', '~>1.3.3'
#https://github.com/bfeher/BFPaperTabBarController
#pod 'BFPaperTabBarController', '~>2.1.13'
#https://github.com/yuping1989/YPTabBarController
#pod 'YPTabBarController', '~>2.0.1'
#https://github.com/Ramotion/animated-tab-bar   IOS8+
#pod 'RAMAnimatedTabBarController', '~>1.5.3'
